backend:
  name: git-gateway
  branch: main
media_folder: public/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
i18n:
  structure: multiple_folders
  locales: [en, es, ch]
  default_locale: es
collections:
  - name: pages
    label: Pages
    i18n:
      structure: single_file
      locales: [en, es, ch]
    files:
      - name: about
        label: About Page
        file: content/home
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
