backend:
  name: git-gateway
  branch: main
media_folder: public/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
collections:
  - label: Home
    name: home
    folder: content/home
    create: true
    fields:
      - label: Title
        name: title
        widget: object
